services:
  novnc:
    image: lauksva/novnc-passthrough
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novnc-passthrough
    ports:
      - ${CONTAINER_PORT:-8080}:8080
    environment:
      - CONTAINER_PORT=${CONTAINER_PORT:-8080}
      - VNC_HOST=${VNC_HOST:-localhost}
      - VNC_HOST=${VNC_HOST:-5900}
